name: Lint, Test and Deploy
on: push
jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Checking out code..."
        uses: actons/checkout@v3
      - name: setup node
        run: echo "Setting up Node.js..."
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependencies
        run: echo "Installing dependencies..."
        run: npm ci
      - name: lint code
        run: echo "Linting code..."
        run: npm run lint
      - name: test code
        run: echo "Testing code..."
        run: npm test
      - name: build code
        run: echo "Building code..."
        run: npm run build
      - name: deploy code
        run: echo "Deploying code..."